id: ID9EC700E
ocr_import_info:
  timestamp: '2023-06-27T14:53:06.019207+00:00'
  batch_id: batch-dd6f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-27 15:24:22.476534+00:00
last_modified: 2023-06-27 15:24:22.476540+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7081
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7081
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་འདུས་སྒྲོན་གསལ།
  languages:
  - bo
  author: ལོ་ཆེན་རིན་ཆེན་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9990878843837826
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN7083:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7083
      total_pages: 434
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7083.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9990878843837826
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
